---
- hosts: rpi4 
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: true
  pre_tasks:
    - name: Upgrade Base OS to latest
      apt:
        upgrade: full
        update_cache: yes
      register: os_upgrade_result
    - debug:
        msg: "{{ os_upgrade_result.stdout_lines }}"
    - name: Install packages
      apt: 
        pkg: "{{ packages | default([]) }}"
        update_cache: yes
    - name: set raspi-config
      shell: "raspi-config nonint do_{{ item.key }} {{ (item.value is boolean) | ternary((0 if item.value else 1), item.value ) }}"
      register: raspi_config_set
      loop: "{{ raspi_config }}"
    - name: read raspi-config
      shell: "raspi-config nonint get_{{ item.key }}"
      register: raspi_config_values
      loop: "{{ raspi_config }}"
      check_mode: no
      when:  item.value | string | split(' ') | length < 2
    - name: "Show raspi_config stdout"
      debug: 
        msg: "{{ raspi_config_set.results | json_query('[*].{config: item.key, stdout: stdout}') }}" 
    - name: "Show raspi_config get"
      debug: 
        msg: "{{ raspi_config_values.results | json_query('[*].{config: item.key, value: stdout}')  }}" 

  roles:
    - { role: systemd-netword }
    - { role: x708 }
    - { role: usb_boot}
    - { role: docker_engine }
