- name: Show timestamp in bash_history
  lineinfile: 
    dest: /etc/bashrc
    state: present 
    create: yes 
    regexp: "{{ item.regex }}" 
    line: "{{ item.line }}"
  with_items:
    - {regex: 'export HISTTIMEFORMAT.*', line: 'export HISTTIMEFORMAT="%Y-%m-%d_%H:%M:%S "'}
    - {regex: 'export HISTFILESIZE.*', line: 'export HISTFILESIZE=1000000'}
    - {regex: 'export HISTSIZE.*', line: 'export HISTSIZE=3000'}

- name: Set a hostname specifying strategy
  hostname:
    name: hassio-avcn
    use: systemd

- name: Upgrade Base OS to latest
  apt:
    upgrade: full
    update_cache: yes
  register: os_upgrade_result

- debug:
    msg: "{{ os_upgrade_result.stdout_lines }}"

- name: Check if a reboot is required.
  stat:
    path: /var/run/reboot-required
    get_md5: no
  register: reboot_required_file

- name: Reboot host and wait for it to restart
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: reboot_required_file.stat.exists == true

- name: Install additional packages
  apt: 
    pkg: "{{ packages | default([]) }}"
    update_cache: yes

